version: 2.1

executors:
  php_executor:
    docker:
      - image: circleci/php:8.4-node-browsers
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          DB_CONNECTION: mysql
          DB_DATABASE: laravel
          DB_USERNAME: root
          DB_PASSWORD: root
      - image: circleci/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel

jobs:
  prepare:
    executor: php_executor
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: sudo apt-get update && sudo apt-get install -y unzip
      - run:
          name: Install Composer Dependencies
          command: composer install --prefer-dist --no-dev --no-interaction --no-progress --optimize-autoloader
      - run:
          name: Set Up Laravel Environment
          command: cp .env.example .env
      - run:
          name: Generate Application Key
          command: php artisan key:generate
      - run:
          name: Cache Configurations
          command: php artisan config:cache

  test:
    executor: php_executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: composer install --no-interaction --prefer-dist
      - run:
          name: Run Database Migrations
          command: php artisan migrate --force
      - run:
          name: Run Tests
          command: php artisan test --no-interaction

workflows:
  version: 2
  laravel-workflow:
    jobs:
      - prepare
      - test:
          requires:
            - prepare
